# Generated by Django 2.2.10 on 2020-04-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
    ]
