# Generated by Django 3.0.7 on 2020-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20200625_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='allow_registration',
            field=models.BooleanField(default=False),
        ),
    ]
