# Generated by Django 3.0.7 on 2020-08-17 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_class_allow_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('droplet', '0003_auto_20200401_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droplet',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
        migrations.AlterField(
            model_name='droplet',
            name='droplet_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='droplet',
            name='image',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='droplet',
            name='initial_password',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='droplet',
            name='ip_addr',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='droplet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='droplet',
            name='region',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
