# Generated by Django 3.0.7 on 2020-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droplet', '0004_auto_20200817_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droplet',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
