# Generated by Django 3.0.7 on 2020-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droplet', '0005_auto_20200817_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droplet',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
